/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountDropdown: typeof import('./src/components/AccountDropdown.vue')['default']
    AccountInfo: typeof import('./src/components/AccountInfo.vue')['default']
    AddButton: typeof import('./src/components/AddButton.vue')['default']
    AddForm: typeof import('./src/components/AddForm.vue')['default']
    AddUpdateForm: typeof import('./src/components/AddUpdateForm.vue')['default']
    AdminCalendar: typeof import('./src/components/AdminCalendar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AttendanceCard: typeof import('./src/components/AttendanceCard.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ClassFinderForm: typeof import('./src/components/ClassFinderForm.vue')['default']
    FilterForm: typeof import('./src/components/FilterForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    ProfileDropdown: typeof import('./src/components/ProfileDropdown.vue')['default']
    RecommendedClasses: typeof import('./src/components/RecommendedClasses.vue')['default']
    RecommendedResources: typeof import('./src/components/RecommendedResources.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateForm: typeof import('./src/components/UpdateForm.vue')['default']
  }
}
